### ISSUE TITLE
when use prism proxy - GET/HEAD can't have body error

### ISSUE THREAD

**Issue by ram-potla** [stoplightio/prism#1408] opened 2020-09-11 06:42 UTC
## To Reproduce

1 .feed openspec to prism 
2. run prism mock severs
3. get response ok as per spec.

4. when prism proxy spec.yaml localhost:<port> --errors

I see below error.
{
    “type”: “TypeError”,
    “title”: “Request with GET/HEAD method cannot have body”,
    “status”: 500,
    “detail”: “”
}

**Environment:**
 - OS: mac mojave
 - node: v14.10.0
 - prism: 4.0.1

spec: openapi: 3.0.1
info:
  title: dfdfsdfdf
  license:
    name: Apache 2.0
    url: http://springdoc.org
  version: 1.4.6
servers:
  - url: http://localhost:9000
    description: Generated server url
tags:
  - name: name
    description: description
paths:
  /api/v1/employees:
    get:
      tags:
        - employee
      summary: employees
      description: Fetches all engineers from db
      operationId: fetchAll
      parameters:
        - name: Content-Type
          in: header
          required: false
          schema:
            type: string
            default: application/json
        - name: Accept
          in: header
          required: true
          schema:
            type: string
        - name: X-type
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'

**Comment by philsturgeon** [comment] 2020-09-11 08:15
Mind if I ask why GET or HEAD has a body? :) 

>  A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing implementations to reject the request.

https://tools.ietf.org/html/rfc7231#section-4.3.1

**Comment by XVincentX** [comment] 2020-09-11 18:49
Yeah same here — this is something we really advice *not* to do.

I'm closing this since it's the behaviour we want; we can keep the conversation going on if you think it's beneficial.

**Closed by XVincentX** 2020-09-11 18:49 UTC
Labels: bug

**Comment by ram-potla** [comment] 2020-09-11 23:42
Not sure why this has been closed . I am not sending any requestbody with get method 
. It works with mock servers but not with real api when use proxy command

**Comment by shaurmanchic** [comment] 2020-10-05 15:25
@XVincentX I'm experiencing the same issue _**Request with GET/HEAD method cannot have body**_, and I have a similar setup: 
`    get:
      operationId: getStatus
      summary: GetStatus
      parameters:
        - $ref: '#/components/parameters/status'
      responses:
        '200':
          $ref: '#/components/responses/Response'`

`  parameters:
      status:
        name: status
        in: header
        required: true
        schema:
          type: uuid`

As you can see, no RequestBody. This is in accordance with spec: https://swagger.io/docs/specification/describing-parameters/

**Comment by XVincentX** [comment] 2020-10-05 16:23
@ram-potla For some reason I've missed the message.

From the error message, it looks that you're sending a body with a GET request; the example you provided is not well formatted and I struggle to reproduce the issue.

If you could set up a better scenario, I can take a look into. 

Cheers!
