### ISSUE TITLE
Error on adding external PDF file to response 

### ISSUE THREAD

**Issue by AhsanShuvo** [stoplightio/prism#1248] opened 2020-06-18 14:27 UTC
**Describe the bug**
When I send a request to get a pdf file from postman, I get this error:
```
{
    "type": "https://stoplight.io/prism/errors#UNKNOWN",
    "title": "Cannot find serializer for application/pdf",
    "status": 500,
    "detail": ""
}
```
I was following their procedure to add external file to response from [here](https://swagger.io/docs/specification/adding-examples/)

**To Reproduce**

my yaml file looks like this:
````
responses:
        200:
          description: Requested Report in PDF format
          content:
            application/pdf:
              schema:
                type: string
                format: binary
              example:
                sampleFile:
                  summary: A sample file
                  externalValue: 'A valid url of pdf file`
```

**Comment by XVincentX** [comment] 2020-06-18 14:30
@AhsanShuvo 

That is a know limitation. In particular:

1. We do not support the externalValue in OpenAPI (yet) #1155 
2. We do not support returning binary files

We want to support this, but it's not exactly our top priority at the moment.

I'm closing this as a duplicate of #1155

**Closed by XVincentX** 2020-06-18 14:30 UTC
Labels: bug

**Comment by elev8studio** [comment] 2022-05-04 11:33
Two years on, why has this not been implemented yet? I need this. Is there perhaps a workaround?
