### ISSUE TITLE
Enable Docker images for linux/arm64

### ISSUE THREAD

**Issue by rngtng** [stoplightio/prism#2312] opened 2023-06-20 21:18 UTC
## Context

I figured the prism docker images are only available for `linux/amd64` architectures. As of this running prism on Apple silicon machines is virtualized with reduced performance. I successfully build an arm64 image locally w/o any modification, so it looks like
it's 'just' a matter of enabling it.

## Current Behavior

Running the latest docker image produces the warning, indicating that an amd64 arch image is used, so performance will be reduced due to virtualization.

```
$ docker run stoplight/prism
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

## Expected Behavior

No warning, as an image for `linux/amd64` arch is found

## Possible Solution(s)

Make use of `docker buildx` to enable multi arch build. Alternatively build the arm image explicit. https://www.docker.com/blog/multi-arch-images/

Let me know how you build and push to docker hub. Happy to advice you further.

**Comment by chohmann** [comment] 2023-06-23 16:36
Duplicate of #1966. Closing.

**Closed by chohmann** 2023-06-23 16:36 UTC

**Comment by rngtng** [comment] 2023-06-23 17:22
@chohmann oh ups - Sorry I didn’t saw the original issue. My bad
