### ISSUE TITLE
Prism : Improved HATEOAS mocking for links in the body

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#434] opened 2019-07-06 20:54 UTC
APIs with links in the body are currently suffering, it outputs the URL in the description document, not the URL of the current host. This makes it hard for clients to implement HATEOAS flows.

Implementation ideas discussed in GitHub issue.

https://github.com/stoplightio/prism/issues/238

**Comment by XVincentX** [comment] 2019-07-08 10:10
Duplicate of #238

**Closed by XVincentX** 2019-07-08 10:10 UTC
