### ISSUE TITLE
Prism wont return bad responses

### ISSUE THREAD

**Issue by omernave1** [stoplightio/prism#745] opened 2019-10-28 09:01 UTC
I am using Prism on my OAS3 api. I have multiple responses for every path, including error 400/404/401.

I can't get prism to respond with any bad response even when I send a bad body in the request or trying to get to an object that doesn't exists.

**Expected behavior**
Prism should be able to respond not only with 2xx responses.

**Environment (remove any that are not applicable):**
 - Library version: Latest
 - OS: macOS

**Comment by XVincentX** [comment] 2019-10-28 12:01
Hey @omernave1,

Prism generally validates the payload you're sending in and in case it's invalid, it will effectively respond with an error response based on what you have described in the document or in worst case it will generate an error message for you.

Would it be possible to share the document you're working with as well as the actual http call you're doing to the server?

**Comment by lag-of-death** [comment] 2019-10-28 14:51
Hi @omernave1, thank you for the report.

Unfortunately, so far, I have not been able to reproduce this. I would love to take a look at your OAS document and the requests used against Prism though.

There were no failed tests for `3.1.1` release (`macOS` build included).

If you want to take a look at example OAS documents and the requests associated with it, these might be of interest to you:

1. 401 response: https://github.com/stoplightio/prism/blob/master/test-harness/specs/security/security-scheme-validation-AC-2.oas3.txt
2. 404 response: https://github.com/stoplightio/prism/blob/master/test-harness/specs/selecting-examples/manually-select-examples-AC-2.oas3.txt
3. 422 response (invalid JSON payload): https://github.com/stoplightio/prism/blob/master/test-harness/specs/validate-body-params/json-invalid-request-2.oas3.txt
4. 422 response (invalid `x-www-form-urlencoded` payload): https://github.com/stoplightio/prism/blob/master/test-harness/specs/validate-body-params/form-data-invalid-request.oas3.txt
5. 401 response (overriding the default 401 response): https://github.com/stoplightio/prism/blob/master/test-harness/specs/security/security-scheme-validation-AC-20.oas3.txt
6. 400 response: https://github.com/stoplightio/prism/blob/master/test-harness/specs/empty-responses/empty-responses-AC-8.oas3.txt

Also, under https://github.com/stoplightio/prism/tree/master/test-harness/specs, you can find many more examples, that you can try out locally. 
The content between `====spec====` and `====server====` is an OAS document that you can start Prism with and test it with the command embedded in that spec file.

**Comment by XVincentX** [comment] 2019-10-31 20:18
@omernave1 Can you provide more details? Otherwise I will have to close this as Can't Reproduce

**Closed** 2019-11-01 16:24 UTC
Labels: bug
