### ISSUE TITLE
$ref on `paths` not working

### ISSUE THREAD

**Issue by andresblancomorales** [stoplightio/prism#451] opened 2019-07-11 19:17 UTC
**Describe the bug**
OpenApi files with references under `paths` are not loaded.

**To Reproduce**

1. Given this OpenAPI document:
```spec.yaml
openapi: "3.0.0"

info:
  title: An API
  version: 0.1.0

servers:
  - url: http://{baseURL}/v1
    variables:
      baseURL:
        default: api.company.com
        description: Base URL

tags:
  - name: Anonymous
    description: Endpoints exposed for anyone to consume

paths:
  /accounts:
    $ref: 'anonymous/accounts.yaml'
```

Anonymous/accounts.yaml:
```anonymous/accounts.yaml
post:
  summary: Creates a new account
  requestBody:
    description: the account data to use to create the account
    required: true
    content:
      application/json:
        schema:
          $ref: 'schemas.yaml#/components/schemas/account'
  responses:
    201:
      description: Created
      content:
        application/json:
          schema:
            type: string
            example: '{"accountId": "1c69145a-5029-490e-8e1b-11d427ebed15"}'
  tags:
    - Anonymous
```
2. Run prism CLI with -d flag
3. See error: No operations found in the current file

**Expected behavior**
Load /accounts path

**Environment (remove any that are not applicable):**
 - Library version: docker stoplight/prism:3

**Comment by XVincentX** [comment] 2019-07-12 06:56
@andresblancomorales,

This is a duplicate of #390 — I'm going to close this so we can continue the discussion there.

**Closed by XVincentX** 2019-07-12 06:56 UTC
Labels: bug
