### ISSUE TITLE
Prism (v3) : Traffic Recording

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/prism#431] opened 2019-07-06 20:52 UTC
Prism CLI should have a new `prism record` command. The user supplies two required arguments "upstream URL" and Spec filepath.

the upstream URL is where traffic should be sent, and we run very similar code to the validation server (same proxy logic) but instead of running validation on the incoming request, we update an internal instance of Graphite, and then write to the file when the server is stopped. 

This will need to support rather complex cases, and improve existing specs and operations instead of just replacing them. For example, a request with "foo": "bar" and then "foo": 123 should be writing oneOf's to support both those types, and not just replacing with whichever came in second.

**Comment by philsturgeon** [comment] 2019-07-15 17:08
duplicate of #423

**Closed by philsturgeon** 2019-07-15 17:08 UTC
