### ISSUE TITLE
Dynamic data returning negative numbers, even if add the minimum 

### ISSUE THREAD

**Issue by nicolastakashi** [stoplightio/prism#1098] opened 2020-04-22 12:23 UTC
**Describe the bug**
Dynamic response returning negative numbers, even if add the minimum and mark the format as int32.

**To Reproduce**

1. Given this OpenAPI document 

```yaml
openapi: 3.0.0
info:
  title: API
  description: API.
  version: v1
  contact:
    email: email@email.com
    name: Contato
tags:
  - name: items
paths:
  /items:
    get:
      operationId: get-items
      summary: summary
      description: description
      tags:
        - items
      parameters:
        - in: query
          description: description
          name: param1
          schema:
            type: integer
            format: int32
            default: 1
            minimum: 1
        - in: query
          description: description
          name: param2
          schema:
            type: integer
            format: int32
            default: 10
            minimum: 10
            maximum: 100
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  a:
                    type: integer
                    format: int32
                    minimum: 0
                  b:
                    type: integer
                    format: int32
                    minimum: 0
                  c:
                    type: integer
                    format: int32
                    minimum: 0

```

2. Run this CLI command 

```bash 
prism mock api.yaml -d
```

3. See error
Returns negative numbers

**Expected behavior**
Since the definition is designed as integer with a minimum value non-negative, it must return only signed numbers.

**Screenshots**
![image](https://user-images.githubusercontent.com/8205546/79980875-a9b17c80-849b-11ea-977f-6e4ab6bb8f60.png)

![image](https://user-images.githubusercontent.com/8205546/79980952-c8b00e80-849b-11ea-9105-31b685290164.png)

![image](https://user-images.githubusercontent.com/8205546/79981050-f006db80-849b-11ea-84fc-5880f2acdb2c.png)

**Environment (remove any that are not applicable):**
 - Library version: 3.3.3
 - OS: Ubuntu 18.04
 - Browser: All browsers

**Comment by philsturgeon** [comment] 2020-04-29 09:37
I've noticed this before and completely forgot to file an issue, thank you @nicolastakashi! 

@XVincentX @karol-maciaszek Is this a json-schema-faker thing we can help them with?

**Comment by XVincentX** [comment] 2020-04-29 11:57
@karol-maciaszek 's on it.

**Comment by karol-maciaszek** [comment] 2020-04-29 13:49
> @XVincentX @karol-maciaszek Is this a json-schema-faker thing we can help them with?

ATM the diagnosis is that is is a problem with [http-spec](https://github.com/stoplightio/http-spec) package. The internal representation of the spec has wrong min/max values:
```
              "properties": {
                "a": {
                  "type": "integer",
                  "format": "int32",
                  "minimum": -2147483648,
                  "maximum": 2147483647
                },
```

I'm looking now at [http-spec](https://github.com/stoplightio/http-spec)

**Comment by karol-maciaszek** [comment] 2020-04-29 14:50
Ok, found. The issue is in a dependent library which we're using for converting OpenAPI schema to JSON Schema - [@openapi-contrib/openapi-schema-to-json-schema](https://github.com/openapi-contrib/openapi-schema-to-json-schema/).

The bug is placed here: https://github.com/openapi-contrib/openapi-schema-to-json-schema/blob/b95c27de775ba4c1b16a636ed51860e9a65552ab/lib/converters/schema.js#L174.

When the format is set to int32, int64 and so on it completely ignores previously given minimum/maximum values and uses these defined for the format.


I believe the flow in that lib should be fixed to: if there is min/max set then don't add those defined by int32/.. format.
Or even better, instead of ignoring it should verify that user-given min/max is within the min/ax of the format and the choose appropriate value.

@nicolastakashi if you want a quick workaround, just drop the format field and it will work immediately

I will create also a PR to [@openapi-contrib/openapi-schema-to-json-schema](https://github.com/openapi-contrib/openapi-schema-to-json-schema/) with a proposed fix.

**Comment by karol-maciaszek** [comment] 2020-04-29 15:07
Aha, one more thing. The reason it works in query is that the schema is not converted to JSON Schema for queries. Which seems to be a bug, right @philsturgeon @XVincentX ?

**Comment by nicolastakashi** [comment] 2020-04-29 16:35
Hey @karol-maciaszek, thank you so much to reply :smile: 

I tried to help you guys, but I could understand well the flow, sorry about that.

Thanks for the suggestion about the format, for now, this is not a problem for me, I reported the issue because of its makes sense.

**Comment by XVincentX** [comment] 2020-07-27 09:18
@nicolastakashi Hey!

The issue has been fixed on the upstream dependency and it should be in the latest Prism version. Feel free to reopen in case you still experience this.

**Closed by XVincentX** 2020-07-27 09:18 UTC
Labels: p/longterm, team/platinum-falcons
