### ISSUE TITLE
Prism support for multipart/form-data content type

### ISSUE THREAD

**Issue by spaul90** [stoplightio/prism#1012] opened 2020-03-02 12:48 UTC
**Describe the bug**
We are trying to mock Auth API via prism. The content type for the request is supposed to be multipart/form-data. However, prism doesn't accept that. It works only if the content type is application/json.

**To Reproduce**
Run prism mock command: prism mock -d api.yml
Call the auth api with content-type: multipart/form-data. 

**Expected behavior**
This should result in 200 OK response. 

**Actual behavior**
This is returning 400 Bad Request with sl-violations.

**Environment (remove any that are not applicable):**
Prism version: 3.2.9

**Additional context**
Auth Api definition
```
/oauth2/token:
    post:
      summary: Get Auth Token
      description: Get a token to use the API
      operationId: getToken
      tags:
        - auth
      parameters:
        - in: header
          name: Authorization
          required: true
          description: 'Standard Basic auth header containing client_id:client_secret'
          schema:
            type: string
            pattern: "^Basic \\S+$"
      requestBody:
        description: The token request
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                grant_type:
                  enum:
                    - client_credentials
```

**Comment by XVincentX** [comment] 2020-03-02 17:18
Hey,

we effectively support `application/json` and `application/x-www-form-urlencoded` — the `multipart/form-data` Is usually for binary uploads which at the moment are not handled by Prism (they are hard — so to speak).

Given your use case though, I think `application/x-www-form-urlencoded` would work for you. Why are you using multipart in this specific case?

I'm closing this since it's by design — feel free to reopen in case.

**Comment by XVincentX** [comment] 2020-03-02 17:22
Duplicate of #432

**Closed by XVincentX** 2020-03-02 17:22 UTC
Labels: enhancement

**Comment by spaul90** [comment] 2020-03-03 09:39
Thanks for your help.
We have no special reason to go for content type multipart/form-data. We updated the definition to use application/x-www-form-urlencoded and all good now.

**Comment by gap777** [comment] 2021-06-01 18:20
Doesn't seem like `application/x-www-form-urlencoded` is at all suitable for file upload scenarios. For efficiency reasons, the API that allows large file uploads should be `multipart/form-data` -- prism should be extended to support that.
c.f. https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
