### ISSUE TITLE
PRISM adds randomly attributes to response payload

### ISSUE THREAD

**Issue by jschaefer77** [stoplightio/prism#1776] opened 2021-04-15 09:27 UTC
## Describe the bug

My OpenAPI model has only one attribute (id). PRISM adds randomly attributes to that model, which is confusing.

## To Reproduce

In OpenAPI file:
Define a model with only one attribute (id).
Define a path and use the model the response. (it doesn't matter if it is an array or single response)

PRSIM:
Now run prism via cli (dynamic mode) or in Stoplight studio desktop. (result is the same)

Result:
PRISM adds randomly attributes to the response payload, which is really confusing.

## Expected behavior
PRISM should not add any attributes to the response payload others then the defined 
ones in the OpenAPI file.

## Additional context

**Screenshots**
![random-attributes](https://user-images.githubusercontent.com/52877209/115909941-787fd980-a46c-11eb-8500-c5f36cf474ac.png)

**Environment (remove any that are not applicable):**
 - Library version: 4.1.2
 - OS: Windows 10
 - Browser:
 - Platform: desktop

**Comment by chohmann** [comment] 2021-05-27 18:57
@jschaefer77 those additional properties are being added in dynamic mode because your spec doesn't define `additionalProperties: false` for the model used for the response.

According to the [spec](https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties) additional properties defaults to true:

>By default any additional properties are allowed.

If you don't want these additional properties to be included in the dynamic response from prism, you can add `additionalProperties: false` to your model like so:

```
openapi: 3.0.0
info:
  title: Test API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/dog/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get A Dog
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
components:
  schemas:
    Dog:
      title: Dog
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
```

I'm going to close this issue as Prism is working as intended, but feel free to re-open or ask any additional questions you may have!

**Closed by chohmann** 2021-05-27 18:57 UTC
Labels: p/medium, t/bug, triaged
