### ISSUE TITLE
Detect unresolvable cirular $refs during prism startup

### ISSUE THREAD

**Issue by patrickp-bosch** [stoplightio/prism#891] opened 2019-12-10 08:58 UTC
**User story.**
As an API mock tester, when I startup PRISM and my OpenAPI spec contains an unresolvable $ref, then I want to receive a notification, so that I can try to fix the problem without having to try to fire that request against the mock by myself.

**Is your feature request related to a problem?**
i have tried to get started with PRISM and I have a spec with DTO models externalized into a separate file. My spec is affected by [bug #390](https://github.com/stoplightio/prism/issues/390).
If you experiment with the $refs, you need to try some calls before you know if it works or not.
`[15:43:16] » [CLI] ►  start     Prism is listening on http://127.0.0.1:4010`
(...) I'm firing a call manually with Postman (...)
`[15:43:38] »     [NEGOTIATOR] √  success   Found a compatible content for */*
(node:10040) UnhandledPromiseRejectionWarning: Error: Your schema contains $ref. You must provide specification in the third parameter.`

**Describe the solution you'd like**
During startup, Prism tries to resolve the $refs and outputs a warning if calls use unresolvable $refs.

**Additional context**
Go with a "Fail fast" approach

**Comment by XVincentX** [comment] 2019-12-12 09:56
@patrickp-bosch Thanks for writing us. Would it be possible to get the specification file that's causing the problem or a minimal repro? Prism should indeed fail fast on the ref resolution and that particular error is caused by something else

**Comment by patrickp-bosch** [comment] 2019-12-13 13:49
Thanks for responding, @XVincentX . I am not allowed to disclose the whole API specification files. I have tried to create a minimal reproducible example. So far, I was not able to reproduce the problem with a minimized variant of the specification. Unfortunately, the resource that I try to fetch has plenty of $ref's to other DTOs (especially because we must consider nested DTO references), so it would take a lot of time to try it out one by one. Now the next question is: Is it possible to reflect in the error output which particular $ref prism could not resolve?

**Comment by XVincentX** [comment] 2019-12-13 14:30
@patrickp-bosch — the thing is that such error is coming from an internal library that we do not control and it's not printing the unresolved reference; moreover, that library should *never* see references because we're solving them ahead of the time and we do report errors when some reference goes undefined for some reason (see `getHttpOperations.ts`, line 32).

Unfortunately I do not see any other way to help you unless you can share a reproducible example.

Any chance you've got a circular reference?

**Comment by albertpastrana** [comment] 2019-12-16 11:47
Hey both. I'm having the same issue and I've seen my api docs generator is generating a weird circular reference.

@XVincentX you were asking about it because prism doesn't support recursive data types?

**Comment by XVincentX** [comment] 2019-12-16 12:19
I think it's related to some issues with our resolver for circular references, but I'd need a reference document or something to tackle down the issue :)

If you can share the offending document, that'd be just great!

**Comment by albertpastrana** [comment] 2019-12-16 14:14
Sure! I've seen different flavours of the error, depending on the exact schema. This is the minimum schema I've seen to fail:
```json
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "The API",
    "version" : "0.1"
  },
  "paths" : {
    "/endpoint" : {
      "get" : {
        "operationId" : "getEndpoint",
        "responses" : {
          "200" : {
            "description" : "",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Recursive"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Recursive" : {
        "oneOf" : [
          {
            "$ref" : "#/components/schemas/Recursive1"
          },
          {
            "$ref" : "#/components/schemas/Recursive2"
          }
        ]
      },
      "Recursive1" : {
        "allOf" : [
          {
            "$ref" : "#/components/schemas/Recursive"
          },
          {
            "required" : [
              "prop1"
            ],
            "type" : "object",
            "properties" : {
              "prop1" : {
                "type" : "string"
              }
            }
          }
        ]
      },
      "Recursive2" : {
        "allOf" : [
          {
            "$ref" : "#/components/schemas/Recursive"
          },
          {
            "required" : [
              "prop2"
            ],
            "type" : "object",
            "properties" : {
              "prop2" : {
                "type" : "string"
              },
              "index" : {
                "type" : "string"
              }
            }
          }
        ]
      }
    }
  }
}
```

Also, during my tests I've seen (or at least I think I've seen ;-)) it working when generating it dynamically but failing without the `-d`.

Thanks for your help.

Btw, the schema is autogenerated using https://github.com/softwaremill/tapir

**Comment by XVincentX** [comment] 2019-12-16 15:26
Ok in case of circular references — our ref resolver will effectively "give up" after a certain amount of iterations since it would otherwise end up in a infinite document and we do not "lazily" evaluate the document (which is a way to handle circular references). 

I'm going to keep this issue open but I would consider this kind of an edge case; but I'll bring this up internally in Stoplight and see if we're going to come up with something else. Thanks!

**Comment by albertpastrana** [comment] 2019-12-16 16:34
Thanks for looking into it @XVincentX.
Just wanted to add that in our codebase this is not an edge case but something pretty common when we deal with ADTs, so it'd be great if this can be fixed.
In case you don't have plans to fix it, I'd really appreciate if you can tell us, as this may be a blocker in our adoption to prism and we may need to look for an alternative.
In any case, thanks a lot for open sourcing it, it's great and it works really well in the other scenarios :)

**Comment by wackykid** [comment] 2019-12-17 07:16
oh well... it's funny that with so many ppl facing this issue and that it is not unusual to have circular references,.. seems that this issue is still considered as "not a priority" thus there are no plans or roadmap on resolving it (as replied in issue #643 )...

anyway since this issue won't be solved in any foreseeable future... i have moved on from prism and looking into other alternative solutions and workarounds... so it's just one customer lost... no big deal..

**Comment by XVincentX** [comment] 2019-12-17 09:19
Hey y'all,

let me give you some context here!

First of all, I understand that this feature is annoying to a lot people (way more than I initially thought, to be honest) — and we clearly want to fix that. 

The major problem we have is that — Prism has been designed with the foreword of receiving a resolved document to operate with.

With circular references, this is clearly impossible, since the resulting document would be essentially infinite. In this regard, our ref-resolver is correctly stopping when it detects a circular references — but Prism is not prepared to handle these.

Now — at the moment we're not carrying any reference information alongside the whole Prism pipeline, and changing this is going to require some efforts that I cannot quantify at the moment. I am going to try to escalate this and see if I can prioritise this, but I can't really give you any guarantees at the moment.

 // @philsturgeon

**Comment by philsturgeon** [comment] 2019-12-17 10:41
@wackykid we don't appreciate that kind of tone around here. You can speak to us professionally and respectfully, or you can leave. We are working with others to resolve this issue, and @XVincentX has already said he is asking around internally to see what we can do about this, so let's keep the conversation constructive and on track.

**Comment by philsturgeon** [comment] 2019-12-17 10:42
@albertpastrana thank you for the recreatable example! @patrickp-bosch does this seem representative of your situation also? 

I remember we fixed one recursive situation, where User would have an "owner" and that owner would be a User. The person who designed that schema did not put nullable in there, so we had an issue that it would just reference forever until some memory limit or recursion limit in node was hit. User > User > User > User > User > User > User > User > User > User > User > User > User > User > User > User > User > User > User > User > User > User > User > User > User > User > ....

We fixed that by suggesting they added nullable because what they were doing was pretty much abusing the spec, and I would not expect any tooling to handle that.

This situation seems a little different though, and it might be something our resolver needs help figuring out. @MikeRalphson mind if I pull you into this? I know you have faced all sorts of recursive nightmares and won, have you faced something like this with oas-kit?

**Comment by philsturgeon** [comment] 2019-12-17 10:44
@XVincentX I think we can do something with our resolver to handle these more advanced ref situations for the entire ecosystem, but in the meantime can we do something with prism to detect a "remaining $ref"? Like, a workaround to say: oh we noticed a $ref is floating around here, better throw that away because it will cause trouble?

**Comment by patrickp-bosch** [comment] 2019-12-18 14:24
> @patrickp-bosch does this seem representative of your situation also?

@philsturgeon So far, I did not find any obvious recursion. I could only check again in 2020, after the seasonal holidays.

> The major problem we have is that — Prism has been designed with the foreword of receiving a resolved document to operate with.

@XVincentX I got an advice from a colleague: In my stoplight studio desktop, I have right-clicked the original, unchanged oas2.yaml file and selected "export OpenAPI". As per our understanding, this creates what you call a _resolved document_ because the result combines the path declarations and the DTO model declarations. The result is some 29 000 lines, which is a lot, but not infinite. I feed this into `prism mock`. Again, it fails with the same error message. This tells me that my issue is not caused (at least not exclusively caused) by our externalized DTO file.

**Comment by albertpastrana** [comment] 2019-12-18 14:48
Hi all. Thanks a lot for looking into this.
For now, I've been able to remove the `allOf` reference from the children and this has allowed us to use prism.
In the future, I'm not sure if we'll face a similar scenario but for now the workaround is good enough.
Again, thanks for open sourcing it, we've already saved so many time using it :-D

**Comment by philsturgeon** [comment] 2019-12-19 12:19
@patrickp-bosch the same [resolver](https://github.com/stoplightio/json-ref-resolver) is used for both "Export OpenAPI" and for reading files into Prism. It should create roughly the same thing, but the outcome could be different. The resolver could give up and leave a $ref in place, and your OpenAPI document would still appear fine, but Prism might choke on that $ref.

Could you Ctrl + F through that 29k line file and see if there are any $ref's left in place?

**Comment by patrickp-bosch** [comment] 2020-01-02 09:37
I did, and I found that in fact, the generated output has one DTO `$ref` which is left unresolved due to a recursive structure that nobody had noticed so far. Thanks for helping to identify this! Best wishes for 2020.

**Comment by philsturgeon** [comment] 2020-01-03 22:21
@patrickp-bosch no worries! We'll keep digging in on the prism side, to see if we can detect these  and bail out gracefully. 

To summarize:

- Hard circular references (e.g: not nullable and therefore A > A > A > A > A > A > A > A > infinity) should simply be avoided
- We need to make sure we don't punish users who make a mistake
- Nice clear error message if possible

**Comment by patrickp-bosch** [comment] 2020-01-07 08:05
Yes, I think your summary is correct and the improvement would be very helpful for many users.

**Comment by sy-tech** [comment] 2020-02-04 14:57
We have run into a similiar issue except of a child ref that points to self as describe above we have a array of child refs that point to itself. I tried making the array nullable but i dont think thats valid swagger.

I assume its the same problem since its a hard circular references just multiple of them each time.

Is there any update on this?

**Comment by XVincentX** [comment] 2020-02-04 14:57
Unfortunately I haven't been able to double down on this yet.

**Comment by XVincentX** [comment] 2020-02-06 16:47
Just a quick update — we have been able to identify a very promising library to resolve the references and apparently it works just great with the circular ones. I'll keep you posted.

**Comment by philsturgeon** [comment] 2020-04-29 10:04
An update for folks, we switched to [json-schema-ref-parser](https://github.com/APIDevTools/json-schema-ref-parser), which is functionally better at resolving various situations. 

We are sending them a few more PRs to bring it up to feature parity with the old json-ref-resolver, then we can migrate Prism over to using it.

**Comment by vintprox** [comment] 2020-04-30 19:08
Would like to bump, since inability to simultaneously retain recursive $ref to same model *and* run "Try It" in [Stoplight Studio](https://github.com/stoplightio/studio).
![image](https://user-images.githubusercontent.com/5708819/80749286-e54ce600-8b2e-11ea-9645-411326acdf43.png)

How do I work around this?

**Comment by philsturgeon** [comment] 2020-04-30 20:35
Aww man, bumping me on an issue I updated _yesterday_? 😂

If you can gimme your OpenAPI I bet we can sort it out. As you can see from above most folks have discovered a wonky aspect to their OpenAPI through this issue and have been able to resolve it, I'm sure we can do the same for you.

**Comment by vintprox** [comment] 2020-04-30 20:39
> Aww man, bumping me on an issue I updated _yesterday_? 😂
> 
> If you can gimme your OpenAPI I bet we can sort it out. As you can see from above most folks have discovered a wonky aspect to their OpenAPI through this issue and have been able to resolve it, I'm sure we can do the same for you.

I just so happened to find rather basic workaround: just don't use self-$ref as array item, leaving just empty object. So, preview seems to be fine with it (not that I am).

**Comment by XVincentX** [comment] 2020-07-01 21:26
After switching to the new resolver, we are now able to detect circular references that we can't handle, and refuse to start Prism. #1270 closes this.

![image](https://user-images.githubusercontent.com/1416224/86293095-99aecb00-bbb7-11ea-9859-158e63188ab6.png)

**Closed** 2020-07-02 15:05 UTC
Labels: bug, team/platinum-falcons

**Comment by black-snow** [comment] 2020-09-22 11:44
I cross-read the issue and I'm wondering what to do now. I have circular refs in my spec and I need a mock server. My spec has an example for the case - why doesn't the server just use this? :|
Can someone please point me into the right direction?

**Comment by XVincentX** [comment] 2020-09-24 16:17
We haven't been able to really tame this down properly yet — the problem is that as much as we can support circular references internally, we will always ultimately fail to serialise them back in a payload.
