### ISSUE TITLE
Dynamic Response generation generates random fields

### ISSUE THREAD

**Issue by williamj20** [stoplightio/prism#2244] opened 2023-03-15 19:29 UTC
When I run prism mock -d spec.yaml, the generated mocked responses generate random fields that are not defined in my spec

## Context

I would like to use Prism to generate mocked api responses based on OpenAPI specs, but when using the dynamic response generator, it seems to generate random fields with no meaning.

## Current Behavior

Prism dynamic response generation generates random fields in the mock api responses. For example, some random field "amet_afd" with some random value -24142591 gets generated as a part of the response, even though this field is never defined anywhere in the openapi specs. 

## Expected Behavior

The generated api responses should match the schemas defined in the openapi specs

**Comment by williamj20** [comment] 2023-03-15 19:36
I realize now this is a duplicate issue described [here](https://github.com/stoplightio/prism/issues/2046). Would be really nice if this could be fixed though

**Comment by chohmann** [comment] 2023-03-17 16:27
Hi @williamj20 yes this is a duplicate of https://github.com/stoplightio/prism/issues/2046. We will look into this as we have capacity. We will continue conversation over on the other issue and close this one.

**Closed by chohmann** 2023-03-17 16:27 UTC
