### ISSUE TITLE
Enable Multi arch Build in DockerHub

### ISSUE THREAD

**Issue by viktorsteinwand** [stoplightio/prism#2467] opened 2024-02-25 18:06 UTC
## User Story Description
As a developer working on a ARM64 CPU (MacOS M1) machine,
I want to have running Prism without emulation,
so I can use Prism without poor performance or failires.

## Acceptance Criteria
- The tags on Docker Hub do contain both, linux/amd64 and linux/arm64 tags

## Sprint Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Team has defined solution / steps to satisfy acceptance criteria
- [ ] Acceptance criteria is verifiable / testable
- [ ] External / 3rd Party dependencies identified

**Comment by brendarearden** [comment] 2024-03-01 17:31
Closing this as a duplicate of https://github.com/stoplightio/prism/issues/1966

**Closed by brendarearden** 2024-03-01 17:31 UTC
