### ISSUE TITLE
Passthrough Binary Request/Response Bodies

### ISSUE THREAD

**Issue by jstys** [stoplightio/prism#1321] opened 2020-07-30 01:13 UTC
## User story.

As a developer, I can proxy requests/responses with binary bodies, so that I can still proxy all requests through prism-cli proxy without having to write reverse proxy rules to ignore certain routes.

## Is your feature request related to a problem?

I'm using apache as a reverse proxy for our app and I'm required to write additional proxy rules for routes which have requests/responses containing binary body data so that prism doesn't distort the payloads.

## Describe the solution you'd like

For me, prism would ideally ignore body validation when `Content-Type` is set to `application/octet-stream` so that basic endpoint validation can still be confirmed i.e. "does the endpoint we're hitting exist in the openapi.yaml file?" 

## Additional context

I've read through some issues which show that binary bodies are not a priority but it would be helpful if there was a way to transparently passthrough the data so these routes could still be used with the prism proxy.

**Comment by XVincentX** [comment] 2020-07-30 07:10
Unfortunately there is no means to do that at the moment. Even though we call it "proxy", Prism is not acting as a proxy and it's not streaming the body up to the upstream server directly; it's indeed parsing and keeping it in memory for validation purposes.

I'll keep this open, but I do not think we're going to work on this in the short term.

**Comment by jstys** [comment] 2020-07-30 12:31
Ok thanks for the explanation, I'll keep an eye on any updates and just rely on my apache config for the time being.

**Comment by philsturgeon** [comment] 2020-09-11 08:17
@XVincentX could we maybe detect mime types and only have prism get involved with things which make sense for it to get involved with?

**Comment by XVincentX** [comment] 2020-09-11 19:01
@philsturgeon I can definitely take a look. 

Notes to myself next week:

Prism Http does not have access to the request object anymore; therefore every http proxy on the Node ecosystem will not work.

On the other hand is to implement this in the http-server package. If the content-type header is effectively an octet stream, just proxy directly from the http server, and skip everything else.

**Comment by philsturgeon** [comment] 2020-09-11 19:50
That’ll work I think! proxy is a CLI and HTTP Server feature not a HTTP Client feature anyway, right? Or did i forget.

--
Phil Sturgeon
DevRel @ Stoplight.io

**Comment by XVincentX** [comment] 2020-09-17 19:11
@jstys Can you clone down #1429 and let me know if that satisfies your use case?

**Comment by XVincentX** [comment] 2020-09-21 16:28
@jstys Would it be possible also to get a reproduction step so that I can test your specific use case scenario?

**Comment by jstys** [comment] 2020-09-22 12:16
@XVincentX Is there an easy way to just switch my existing yarn dependency?  Tried switching to the PR link in package.json but doesn't yield the prism binary when building.

For reproduction, I was sending CSV files as binary resulting in invalid CSV format after routing through prism.

**Comment by XVincentX** [comment] 2020-09-22 13:43
Good point; I am not too sure if that is going to be easy, since we require TypeScript files to be transpired.

Are you using the CLI or the Http client directly? In general, you would need to clone the repository, install the deps and build : `yarn && yarn build` and then spin up the server from there.

**Comment by XVincentX** [comment] 2020-09-25 15:13
> For reproduction, I was sending CSV files as binary resulting in invalid CSV format after routing through prism.

@jstys I also would need the openapi file you were using to test this accordingly.

**Comment by XVincentX** [comment] 2020-10-12 14:29
@jstys Any chance you're going to have time to look into this? Otherwise I am just going to close the issue with the associated PR.

**Comment by XVincentX** [comment] 2020-10-18 20:01
Closing for lack of interest by the stakeholder.

**Closed by XVincentX** 2020-10-18 20:01 UTC
Labels: team/platinum-falcons

**Comment by ilario-pierbattista** [comment] 2022-11-08 17:00
Hi @XVincentX, I am really interested in this feature. Any chance to get this open again?
Do you need feedback for https://github.com/stoplightio/prism/pull/1429 ?
Thanks
