### ISSUE TITLE
Self $ref not working 

### ISSUE THREAD

**Issue by MStumpp** [stoplightio/prism#643] opened 2019-09-23 21:53 UTC
I am using a self ref in swagger spec:

    swagger: '2.0'  
    ...
    definitions:
        SomeModel:
           type: object
           properties:
              ....
              some other properties
              ....
              containingSomeModels:
                 type: array
                 items:
                 $ref: '#/definitions/SomeModel'

When I call the service, I get:

{
    "type": "https://stoplight.io/prism/errors#UNKNOWN",
    "title": "Your schema contains $ref. You must provide specification in the third parameter.",
    "status": 500,
    "detail": ""
}

When i remove property "containingSomeModels" with self reference. it works.

Using: 3.1.1

**Comment by StefanDywersant** [comment] 2019-09-24 09:01
Hey @MStumpp,

I tried to reproduce the issue with the following spec:
```swagger: '2.0'
paths:
  /model:
    get:
      produces:
      - application/json
      responses:
        200:
          schema:
            $ref: '#/definitions/SomeModel'
definitions:
  SomeModel:
    type: object
    properties:
      containingSomeModels:
        type: array
        items:
          $ref: '#/definitions/SomeModelModel'
  SomeModelModel:
    type: object
    properties:
      a:
        type: string
```

Invocation log:
```
(karol@MBP-Karol cli)$ prism --version
3.1.1
(karol@MBP-Karol cli)$ yarn cli mock input.yaml
yarn run v1.17.3
$ node -r ts-node/register -r tsconfig-paths/register src/index.ts mock input.yaml
[CLI] …  awaiting  Starting Prism…
[HTTP SERVER] ℹ  info      Server listening at http://127.0.0.1:4010
[CLI] ●  note      GET        http://127.0.0.1:4010/model
[CLI] ▶  start     Prism is listening on http://127.0.0.1:4010
[HTTP SERVER] get /model ℹ  info      Request received
    [NEGOTIATOR] ℹ  info      Request contains an accept header: */*
    [VALIDATOR] ✔  success   The request passed the validation rules. Looking for the best response
    [NEGOTIATOR] ✔  success   Found a compatible content for */*
    [NEGOTIATOR] ✔  success   Responding with the requested status code 200
```

...and finally, curl log:
```
curl -v http://127.0.0.1:4010/model
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 4010 (#0)
> GET /model HTTP/1.1
> Host: 127.0.0.1:4010
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< access-control-allow-origin: *
< content-type: application/json
< content-length: 41
< Date: Tue, 24 Sep 2019 08:57:23 GMT
< Connection: keep-alive
<
* Connection #0 to host 127.0.0.1 left intact
{"containingSomeModels":[{"a":"string"}]}
```

Could you please provide more details? Especially the spec would be very helpful!

**Comment by MStumpp** [comment] 2019-09-24 10:28
In the initial post, I made a little mistake in model naming. Sorry.
There is only one model "SomeModel" involved.

**Comment by StefanDywersant** [comment] 2019-09-24 10:50
So we are dealing here with possibly infinite recursion, right?

I need to look at our tools how do they deal with such.

**Comment by MStumpp** [comment] 2019-09-24 10:53
That's right. At least I get an error, so prism doesn't crash.

**Comment by kmalhi** [comment] 2019-10-29 01:59
Im getting a similar error. I used prism with https://github.com/stripe/openapi and then sent a GET request to http://127.0.0.1:4010/v1/invoiceitems. Here is the response I got back:
> {"type":"https://stoplight.io/prism/errors#UNKNOWN","title":"Your schema contains $ref. You must provide specification in the third parameter.","status":500,"detail":""}

**Comment by wackykid** [comment] 2019-11-08 02:22
i have the same issue too... i created an model with self reference and an endpoint that returns this model using separate files:

attributes.v1.yaml
```
title: attributes
type: object
properties:
  name:
    type: string
  value:
    type: string
  attributes:
    type: array
    items:
      $ref: ./attributes.v1.yaml
```
test.v1.yaml
```
openapi: 3.0.0
info:
  title: test
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /test:
    get:
      summary: test
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/attributes.v1.yaml
              examples:
                example:
                  value:
                    name: foo
                    value: Bob
                    attributes: null
components:
  schemas: {}
```
when i run prism, i get this error:
```
$ prism mock testapi/reference/test.v1.yaml 
[CLI] …  awaiting  Starting Prism…
[HTTP SERVER] ℹ  info      Server listening at http://127.0.0.1:4010
[CLI] ●  note      GET        http://127.0.0.1:4010/test
[CLI] ▶  start     Prism is listening on http://127.0.0.1:4010
[HTTP SERVER] get /test ℹ  info      Request received
    [NEGOTIATOR] ℹ  info      Request contains an accept header: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    [VALIDATOR] ✔  success   The request passed the validation rules. Looking for the best response
    [NEGOTIATOR] ✔  success   Found a compatible content for text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    [NEGOTIATOR] ✔  success   Responding with the requested status code 200
    [HTTP SERVER] get /test ✖  error     Request terminated with error: Error: AJV validation error: "Error: can't resolve reference ./attributes.v1.yaml from id #"

```
the moment i remove the self reference and it works.

i tried to workaround this by having 2 data models where A ref B and B ref A but it does not solve the issue.

**Comment by wackykid** [comment] 2019-11-08 02:28
> So we are dealing here with possibly infinite recursion, right?
> 
> I need to look at our tools how do they deal with such.

it won't be infinite as long as you don't defined the self-referencing attribute to be required. if and only if the self-referencing attribute is defined as required then you will have an infinite level of recursion and thus it won't be possible to construct such an object.

but if the attribute is optional, the recursion will have to stop somewhere else. it is the responsibilities of the server implementation to ensure that it won't end up stuck in an infinite recursion due to this.

**Comment by Sneh1999** [comment] 2019-11-15 16:40
is there a solution to this yet?

**Comment by XVincentX** [comment] 2019-11-19 10:21
@Sneh1999 Unfortunately we're not actively working on this yet; as this is a bigger problem (the resolving library is something that is used in different parts of the Stoplight ecosystem) this might require a while before it gets the required priority

**Comment by wackykid** [comment] 2019-11-21 05:44
but are there any plans or roadmap on when this issue will be worked on..?

**Comment by XVincentX** [comment] 2019-12-16 15:27
@wackykid We do not at the moment unfortunately. I'm closing this since this is a subset of #891. Thanks!

**Closed by XVincentX** 2019-12-16 15:27 UTC
Labels: bug
