### ISSUE TITLE
Array parameters are considered invalid

### ISSUE THREAD

**Issue by lehphyro** [stoplightio/prism#1320] opened 2020-07-28 15:35 UTC
## Describe the bug

A valid request with a parameter of type array is considered invalid.

## To Reproduce

1. Given this OpenAPI document:
```
openapi: 3.0.3
info:
  title: Test
  version: v1
paths:
  /test:
    get:
      operationId: getList
      parameters:
        - description: Test
          in: query
          name: testParam
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      description: Unique ID
                      type: integer
```
2. Run this CLI command: `prism mock openapi.yaml`
4. Make the request: `GET http://localhost:4010/test?testParam=123`
5. Receive response:
```
{
    "type": "https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY",
    "title": "Invalid request body payload",
    "status": 422,
    "detail": "Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.",
    "validation": [
        {
            "location": [
                "query",
                "testparam"
            ],
            "severity": "Error",
            "code": "type",
            "message": "should be array"
        }
    ]
}
```

## Expected behavior

I expect to have that request be considered valid.

**Environment:**
 - Prism version: [e.g. 3.3.3]

**Comment by XVincentX** [comment] 2020-07-30 08:51
Duplicate of #1306

We'll look into this during our next sprint.

**Closed by XVincentX** 2020-07-30 08:51 UTC
Labels: bug

**Comment by XVincentX** [comment] 2020-08-03 18:08
I can't reproduce this on the latest master branch: <img width="829" alt="image" src="https://user-images.githubusercontent.com/1416224/89213266-1cff7a00-d5c5-11ea-9e8a-83cf48e1f3fd.png">

**Comment by lehphyro** [comment] 2020-08-04 07:40
Thanks, I just confirmed it doesn't happen in the latest release (3.3.6).

**Comment by XVincentX** [comment] 2020-08-04 07:49
Sweet
