### ISSUE TITLE
error when starting the server on 4.1.1

### ISSUE THREAD

**Issue by garryyao** [stoplightio/prism#1546] opened 2020-11-25 11:26 UTC
## Describe the bug

There seemed to be a bug for 4.1.1.

## To Reproduce

1. Given this OpenAPI document
```
openapi: 3.0.0
info:
  title: External APIs
  version: '1.0'
servers:
  - url: 'http://localhost:4010'
    description: local
paths:

```
2. Run this CLI command '....'
```
prism mock ./cypress/mock-server/external-apis.yml --port 4010
```
3. See error
```
TypeError: shim$1.Parser.looksLikeNumber is not a function
    at Object.Yargs.self._parsePositionalNumbers (/Users/garry/workspace/xxx/node_modules/@stoplight/prism-cli/node_modules/yargs/build/index.cjs:2788:31)
    at Object.Yargs.self._postProcess (/Users/garry/workspace/xxx/node_modules/@stoplight/prism-cli/node_modules/yargs/build/index.cjs:2771:25)
    at Object.runCommand (/Users/garry/workspace/xxx/node_modules/@stoplight/prism-cli/node_modules/yargs/build/index.cjs:431:19)
    at Object.parseArgs [as _parseArgs] (/Users/garry/workspace/xxx/node_modules/@stoplight/prism-cli/node_modules/yargs/build/index.cjs:2681:57)
    at Object.get [as argv] (/Users/garry/workspace/xxx/node_modules/@stoplight/prism-cli/node_modules/yargs/build/index.cjs:2635:25)
    at Object.<anonymous> (/Users/garry/workspace/xxx/node_modules/@stoplight/prism-cli/dist/index.js:15:26)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## Expected behavior

Expect to start mock server.

## Additional context
node 14
Not reproducible in `4.1.0`.

**Screenshots**

**Environment (remove any that are not applicable):**
 - Library version: 4.1.1
 - OS: macOS Catalina

**Comment by XVincentX** [comment] 2020-11-25 13:39
Is the issue happening with Node 12 as well? We do not really support Node 14 at the moment.

**Comment by garryyao** [comment] 2020-11-25 13:41
> Is the issue happening with Node 12 as well? We do not really support Node 14 at the moment.

Same thing I'm afraid. 

What's that shim in error?

**Comment by XVincentX** [comment] 2020-11-25 14:00
I cannot reproduce the issue nor in Node 12 nor in Node 14 from a freshly installed Prism by doing `npm i -g @stoplight/prism-cli`.

Can you provide more details to help me reproduce?

**Comment by XVincentX** [comment] 2020-11-25 17:10
Closing until more details are provided.

**Closed by XVincentX** 2020-11-25 17:10 UTC
Labels: bug

**Comment by garryyao** [comment] 2020-12-09 11:46
Hi thanks for checking.

We're still getting this error with `4.1.2`.

Could it be other dependencies that interferes? 

I can provide a full list of our dev dependencies in use below:
```
  "devDependencies": {
    "@stoplight/prism-cli": "4.1.2",
    "@testing-library/jest-dom": "5.11.6",
    "@testing-library/react": "11.2.2",
    "axios-debug-log": "0.8.2",
    "babel-jest": "26.6.3",
    "babel-plugin-rewire-exports": "2.2.0",
    "body": "5.1.0",
    "cypress": "6.0.0",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "1.15.5",
    "eslint": "7.14.0",
    "eslint-config-prettier": "6.15.0",
    "eslint-plugin-react": "7.21.5",
    "husky": "4.3.5",
    "jest": "26.6.3",
    "jest-prop-type-error": "1.1.0",
    "jest-styled-components": "7.0.3",
    "jest-watch-typeahead": "0.6.1",
    "lint-staged": "10.5.2",
    "mjml": "4.7.1",
    "nock": "13.0.5",
    "nodemon": "2.0.6",
    "prettier": "2.2.1",
    "react-test-renderer": "17.0.1",
    "renovate": "19.239.11",
    "supertest": "6.0.1"
  },
```

**Comment by garryyao** [comment] 2020-12-09 11:53
Seemed to be an issue with yargs@16, if I force a resolution to use version 15 of that it seemed to work.
