### ISSUE TITLE
Prism doesn't mock enums 

### ISSUE THREAD

**Issue by DannyCork** [stoplightio/prism#225] opened 2019-04-02 17:13 UTC
Hi,
I am using prism to mock a swagger yml file like so:

```
$ prism mock --spec swagger.yml
Prism version is 2.0.17
Prism mock server started on port 4010
```

The yml file contains an enum as depicted below:

  ```
  region:
                    type: "string"
                    enum:
                      - "a1"
                      - "a2"
                      - "a3"
                      - "a4"
                      - "a5"
                      - "a6"
                      - "a7"
```

When I make a request to the mocked prism server , I note that the response contains the region field however it is not an enum:

```
"region": "incididunt laborum ad in",
or 
"region": "officia"
or 
"region": "voluptate",

etc....
```

Is this observation correct? Does Prism not generate enums from the swagger definition file?

thanks in advance.
Danny.

**Comment by philsturgeon** [comment] 2019-04-03 20:40
Hey @DannyCork, let's figure out what is going on! I was trying to replicate this myself but was running into some trouble, I've been focusing on Prism v3 (the TypeScript rewrite) and couldn't quite get the v2 branch to work. 😅 I ran this up the flag-pole though, so you should get some help in the morning.

**Comment by DannyCork** [comment] 2019-04-04 09:27
many thanks @philsturgeon

**Comment by pytlesk4** [comment] 2019-04-09 16:48
@DannyCork I have tried to reproduce this issue, and have not been successful. Can you provide me with a little bit more info? If I could your full spec that would be super helpful, feel free to email me if you can't post your spec here, tom@stoplight.io.

**Comment by philsturgeon** [comment] 2019-04-29 12:24
I'll close this for now as we could not reproduce and have not heard from you in a bit @DannyCork, but please get in touch if you are still having trouble. We'll need the full spec like Tom said.

**Closed by philsturgeon** 2019-04-29 12:24 UTC
Labels: bug, needs testing
