### ISSUE TITLE
Path parameter proxy validation fails when using oneOf with an integer.

### ISSUE THREAD

**Issue by andrewsomething** [stoplightio/prism#1339] opened 2020-08-10 23:27 UTC
## Describe the bug

I seem to have found an issue where a request will fail proxy validation when a path parameter is specified as `oneOf` a string or an integer, and an integer is used. For example the URL could be:

- `https://example.com/thing/5812605`
- `https://example.com/thing/fbe805e8-866b-11e6-96bf-000f53315a41`

Making a request to the first URL through the proxy fails with the error `should match exactly one schema in oneOf` while the second succeeds as valid.

## To Reproduce

This schema shows the issue:

```yaml
paths:
  /thing/{thing_identifier}:
    get:
      operationId: retrieve_thing
      description: Retrieves the thing
      tags:
        - foo
      parameters:
      - in: path
        name: thing_identifier
        required: true
        description: This will be an integer or a string.
        schema:
          oneOf:
          - type: integer
            description: The int ID.
            example: 6372321
          - type: string
            description: The string ID.
            example: fbe805e8-866b-11e6-96bf-000f53315a41
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  thing:
                    description: The thing
                    type: string
                    example: "This is what you asked for..."
```

Mock it:
```
prism mock -h 0.0.0.0 schema.yaml
```

Proxy it:
```
prism  proxy -h 0.0.0.0 -p 8080 schema.yaml http://0.0.0.0:4010/
```

And make a request:
```
$ curl -X GET -H "Authorization: Bearer token" "http://localhost:8080/thing/5812605" | jq .
{
  "type": "https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY",
  "title": "Invalid request body payload",
  "status": 422,
  "detail": "Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.",
  "validation": [
    {
      "location": [
        "path",
        "thing_identifier"
      ],
      "severity": "Error",
      "code": "oneOf",
      "message": "should match exactly one schema in oneOf"
    }
  ]
}
```

## Expected behavior

I would not expect this request to fail the validation. The integer `5812605` should not not match a string.

Specifying `anyOf` does work around the issue, but I would still expect `oneOf` to work here.

## Additional context

A string passes validation:

```
curl -X GET -H "Authorization: Bearer token" "http://localhost:8080/thing/dgfdgf-2346cfh-456xcgfh" | jq .
{
  "thing": "This is what you asked for..."
}
```

**Environment (remove any that are not applicable):**
 - Library version: 3.3.5
 - OS: Ubuntu 20.04

**Comment by XVincentX** [comment] 2020-08-11 08:04
Possible duplicate of #1294

**Comment by XVincentX** [comment] 2020-08-27 11:00
Ok I have looked into the issue — it's kind of tricky, but here is what it is going on:

`oneOf` is used when you want to make sure only ONE of the schemas passes; so in this specific case we're asking the argument to be either a string or an integer, but not both.

The problem is that, by definition, query string parameter are…strings; so the relative schema is always going to pass, no matter what.

Ajv coerces the value to an integer, passing the validation. When the second validation (string) goes on, it will pass by definition, and that is why the final validation fails.

@philsturgeon do you have any suggestion? While it's technically a perfect valid JSON Schema, the problem is that query strings will always pass a string test, because that's that they are and that's ensured by the protocol. 🤔

**Comment by philsturgeon** [comment] 2020-08-28 15:13
Not much we can do here I suppose, if AIV is going to coerce then it’s gonna be problematic for this sort of oneOf, and we don’t want to start messing with it.

@andrewsomething seeing as query strings are basically always strings, maybe instead of this oneOf you could simply use multiple examples:

```yaml
     parameters:
      - in: path
        name: thing_identifier
        required: true
        description: This will be an integer or a string.
        schema:
          type: string
         examples: 
           number:
             value: 6372321
           uuid:
              value: fbe805e8-866b-11e6-96bf-000f53315a41
```

Then you don’t have to get involved with awkward type handling throughout various components who seek to care or not care.

**Comment by andrewsomething** [comment] 2020-09-03 21:10
I suspected it was something like this. Thanks for investigating!

**Comment by XVincentX** [comment] 2020-09-04 08:40
No problem! Closing this as solved.

**Closed by XVincentX** 2020-09-04 08:40 UTC
Labels: discussion
